---
- name: Define thunderbolt network
  ansible.builtin.template:
    src: thunderbolt-interface.j2
    dest: /etc/network/interfaces.d/thunderbolt
    mode: "644"

- name: Enable IPv4 forwarding
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    regexp: "^#net.ipv4.ip_forward=1"
    line: net.ipv4.ip_forward=1
  notify:
    - reboot

- name: Enable IPv6 forwarding
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    regexp: "^#net.ipv6.conf.all.forwarding=1"
    line: net.ipv6.conf.all.forwarding=1
  notify:
    - reboot

- name: Force reboot
  ansible.builtin.meta: flush_handlers

- name: Install frr package
  ansible.builtin.apt:
    name: frr

- name: Enable the fabricd daemon
  ansible.builtin.lineinfile:
    path: /etc/frr/daemons
    regexp: '^fabricd='
    line: fabricd=yes
  notify:
    - restart frr

- name: Force restart
  ansible.builtin.meta: flush_handlers

- name: Get FRR Version
  ansible.builtin.shell:
    cmd: set -o pipefail && vtysh -c 'show version' | grep FRRouting | awk '{print $2}'
  args:
    executable: /bin/bash
  register: frr_version
  changed_when: false

- name: Set frr version fact
  ansible.builtin.set_fact:
    frr_version: "{{ frr_version.stdout }}"
  changed_when: false

- name: Configure OpenFabric
  ansible.builtin.template:
    src: frr.conf.j2
    dest: /etc/frr/frr.conf
    mode: "640"
    owner: frr
    group: frr
  notify:
    - restart frr

- name: Create frr override directory
  ansible.builtin.file:
    path: /etc/systemd/system/frr.service.d/
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy frr.service drop-in
  ansible.builtin.template:
    src: frr.service.j2
    dest: /etc/systemd/system/frr.service.d/override.conf
    owner: root
    group: root
    mode: "0644"
  notify: daemon-reload
