---
- name: Configure Thunderbolt Network Interfaces
  ansible.builtin.include_tasks: proxmox-tb-net.yml

- name: Ensure modules are loaded and interfaces are up
  ansible.builtin.meta: flush_handlers

- name: Configure Mesh Network over Thunderbolt
  ansible.builtin.include_tasks: openfabric-mesh.yml
